### ISSUE TITLE
X-axis scale

### ISSUE THREAD

**Issue by mfazel** [swannyy14/ggmanh#1]
Hi,

I'm trying to use ggmanh manhattan_plot and noticed all chromosome widths are drawn equally, however, this is not the reality and x-axis is not a pure categorical variable. 
Is there a way to make it scale to the chromosome size? I even noticed in the package vignettes the images are drawn the same way. (https://bioconductor.org/packages/devel/bioc/vignettes/ggmanh/inst/doc/ggmanh.html)

Thanks,
Mehdi

**Comment by leejs-abv** [comment]
Hi Mehdi, you can set the argument `preserve.position` to `TRUE` to use the actual position / scale the width of each chromosomes.

Best,
John

**Comment by mfazel** [comment]
Very nice😃  sorry for the obvious question! somehow I missed this 🤔 probably I was following the vignettes and didn't check the help page for "..."s !
Thanks
Mehdi
