### ISSUE TITLE
Change the color

### ISSUE THREAD

**Issue by chenglishen2018** [swannyy14/ggmanh#3]
![Rplot01](https://github.com/user-attachments/assets/59705cf3-b149-458f-8b64-8aeefee99b76)
I tried to revise the color in the Manhattan plot, but not successful. By default, the colors are repeated, such as genomes 1,9 and 17 are the same color. Can I revise the default color?

**Comment by swannyy14** [comment]
Hi @chenglishen2018 , guide to customizing point color with ggmanh package can be found in [this link](https://bioconductor.org/packages/devel/bioc/vignettes/ggmanh/inst/doc/ggmanh.html#33_Highlighting).

If you wish to color the points based on chromosome using `manhattan_plot()` function, you can pass the column name to the argument `highlight.colname=` and pass a character vector to the argument `highlight.col=`. 

For example, if you have a dataset `data` with `chromosome` as column name, which contains chromosome 1, 2, and X, then specifying manual color would look something like

```
manh_colormap <- c("1" = "red", "2" = "green", "X" = "blue")
manhattan_plot(data = data, ---other necessary arguments---, highlight.colname = "chromosome", highlight.col = manh_colormap)
```
